name: hello-world
on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check-version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for the next step to have the complete git history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Check for version change
        id: version_changed
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true # Search for changes in the last commit

      - name: Install dependencies
        run: npm install

      - name: Build component (if needed)
        run: npm run build

      - name: Publish to NPM
        if: steps.version_changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # Replace custom curl script with Discord Action
      - name: Notify Discord
        if: steps.version_changed.outputs.changed == 'true'
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: ${{ github.actor }} has been successfullly published to main.
